---
assignAutomerge: true
assigneesFromCodeOwners: true
autodiscover: false
binarySource: "install"
branchConcurrentLimit: 25
enabled: true
globalExtends:
  - ":ignoreModulesAndTests"
  - ":dependencyDashboard"
hostRules:
  - hostType: "maven"
    matchHost: "https://maven.pkg.github.com/netcracker"
    token: "{{ secrets.renovation_bot_private_packages_read }}"
packageRules:
  - matchManagers: [ "maven" ]
    matchPackageNames: [ "/.*/" ]
    addLabels: [ "manager:maven" ]
  - matchManagers: [ "dockerfile" ]
    matchPackageNames: [ "/.*/" ]
    addLabels: [ "manager:docker" ]
  - matchManagers: [ "gomod" ]
    matchPackageNames: [ "/.*/" ]
    addLabels: [ "manager:go" ]
  - matchManagers: [ "github-actions" ]
    matchPackageNames: [ "/.*/" ]
    addLabels: [ "manager:github-actions" ]
  - matchPackageNames:
      - "/.*/"
    allowedVersions: "!/.*(redhat|composite|groovyless|jboss|atlassian|preview|does-not-exist|-SNAPSHOT).*/"
platform: "github"
platformAutomerge: true
postUpdateOptions:
  - "gomodUpdateImportPaths"
  - "gomodTidy"
prConcurrentLimit: 25
prCreation: "immediate"
prHourlyLimit: 5
printConfig: false
pruneStaleBranches: true
rebaseWhen: "behind-base-branch"
recreateWhen: "always"
reviewersFromCodeOwners: true
vulnerabilityAlerts:
  addLabels: ["security"]
  vulnerabilityFixStrategy: "lowest"